### ISSUE TITLE
Retained messages

### ISSUE THREAD

**Issue by bloever** [adafruit/Adafruit_MQTT_Library#9]
Hello,

Thanks for a great library. It has been running great for quite a while, but I have recently run into a problem.

I have several topics with retained messages. As long as I only subscribe to one topic at a time everything is working fine. If I however subscribe to two topics (both with retained messages) the second topic will experience a "Failed to subscribe" during connect().

Is this known?

Thanks again for all the work that has went into this library.

**Comment by bloever** [comment]
Hello again,

I have done some more testing on this and implemented a fix that atleast works for me. Retained messages can be sent before the SUBACK message, and since the code is just searching for the first 5 bytes to arrive after a SUBSCRIBE this is not a SUBACK, but actually a PUBLISH message in my case. I'm using Mosca as my MQTT broker.

```c
// Get SUBACK 
len = readPacket(buffer, 5, CONNECT_TIMEOUT_MS); 
DEBUG_PRINT(F("SUBACK:\t")); 
DEBUG_PRINTBUFFER(buffer, len); 
if ((len != 5) || (buffer[0] != (MQTT_CTRL_SUBACK << 4))) { 
    return 6;  // failure to subscribe 
} 
```

I worked around this by implementing the callback feature on each subscribe object and then replacing the code above with a call to a function which reads each following message until a SUBACK is received. This obviously lacks better handling of when a SUBSCRIBE fails, but i thought I could share my findings so far. I was thinking I could implemented the handling of failing a SUBSCRIBE on each Subscription object instead of failing the entire connection. Just an idea. I might be totally wrong.

Anyways, here is what I have done:

in connect();
```c
while((!this->readMessages(subscriptions[i])) && max_retained <= 5) {
     max_retained++;
}
```

readMessages();
```c
bool Adafruit_MQTT::readMessages(Adafruit_MQTT_Subscribe *subscription) {
  // Serial.println("inside readmessages");
  
  // Read the first two bytes to determine what this is and how long the message is
  uint8_t len = readPacket(buffer, 2, CONNECT_TIMEOUT_MS);
  
  if (len == 2) {
    // Correct number of bytes received
    uint8_t TYPE = buffer[0];
    uint8_t LENGTH = buffer[1];
    
    if(TYPE == (MQTT_CTRL_SUBACK << 4)) {
      // SUBACK
      len = readPacket(buffer, LENGTH, CONNECT_TIMEOUT_MS);
      return true;
    }
    
    if(TYPE == (MQTT_CTRL_PUBLISH << 4)) {
      // PUBLISH
      len = readPacket(buffer, LENGTH, CONNECT_TIMEOUT_MS);

      uint8_t skip = 2; // Bytes to skip 
      uint8_t topiclength = (uint8_t)buffer[1]; // Length of topic
      uint8_t payloadlength = LENGTH-skip-topiclength; // Payload length
      
      memset(subscription->lastread, 0, SUBSCRIPTIONDATALEN);

      if (payloadlength > SUBSCRIPTIONDATALEN) {
        payloadlength = SUBSCRIPTIONDATALEN-1; // cut it off
      }

      // extract out just the data, into the subscription object itself
      memcpy(subscription->lastread, buffer+skip+topiclength, payloadlength);
      subscription->datalen = payloadlength;
      subscription->callback((char*)subscription->lastread);
      
      return false;  
    }    
  } else {
     // Invalid length received
  }
  return false;
}
```

**Comment by toddtreece** [comment]
this should be fixed by #10 & the release of Adafruit_MQTT_Library v0.12.0. please reopen this if you still are having issues after updating. thanks for the detailed report!

**Comment by pengu-fr** [comment]
This bug is still present (or is back) in v.0.20.1

I configure 2 feeds : 
```
Adafruit_MQTT_Subscribe feedA = Adafruit_MQTT_Subscribe(&mqtt, MQTT_TOPIC_A);
Adafruit_MQTT_Subscribe feedB = Adafruit_MQTT_Subscribe(&mqtt, MQTT_TOPIC_B);

```
Set callbacks for them and subscribe :
```
  feedA.setCallback(callbackA);
  feedB.setCallback(callbackB);
  mqtt.subscribe(&feedA);
  mqtt.subscribe(&feedB);
```
Both topic have a retain message that should be send right after MQTT client connection.
But I only get the one from the last subscribe() call.

So right now, to get retain messages from both topic for sure, I have to :
```
	mqtt.subscribe(&debugSub);
	MQTT_connect();
	mqtt.processPackets(1000);
	mqtt.disconnect();
	mqtt.subscribe(&intervalSub);

```

**Comment by theonlytruth** [comment]
I have the same problem and can't find a good solution.

My code is based on the [ESP8266 example](https://github.com/adafruit/Adafruit_MQTT_Library/blob/master/examples/mqtt_esp8266/mqtt_esp8266.ino) but instead of one topic I subscribed to three topics. 

```c++
// Setup a feed called 'switch' for subscribing to changes.
Adafruit_MQTT_Subscribe mainswitch  = Adafruit_MQTT_Subscribe(&mqtt, "***/rgb/mainswitch");

// Setup a feed called 'colour' for subscribing to changes.
Adafruit_MQTT_Subscribe colour      = Adafruit_MQTT_Subscribe(&mqtt, "***/rgb/colour");

// Setup a feed called 'brightness' for subscribing to changes.
Adafruit_MQTT_Subscribe brightness  = Adafruit_MQTT_Subscribe(&mqtt, "***/rgb/brightness");
```

And ...

```
  mqtt.subscribe(&mainswitch);
  mqtt.subscribe(&colour);
  mqtt.subscribe(&brightness);
```

In my loop I do nearly the same as in the example but three times:

```
  MQTT_connect();
  Adafruit_MQTT_Subscribe *subscription;
  while (subscription = mqtt.readSubscription(5000)) {
    if (subscription == &colour) {
      Serial.print(F("Got Colour: "));
      colourvalue = atoi((const char*)colour.lastread);
      Serial.println(colourvalue);
    }
    if (subscription == &mainswitch) {
      Serial.print(F("Got Switch: "));
      switchvalue = atoi((const char*)mainswitch.lastread);
      Serial.println(switchvalue);
    }
    if (subscription == &brightness) {
      Serial.print(F("Got Brightness: "));
      brightnessvalue = atoi((const char*)brightness.lastread);
      Serial.println(brightnessvalue);
    }
```

It only reads the last topic's retained message. So I did a workaround according to @pengu-fr . It works but this needs some seconds to start. Is there another better way?
